"use client"

import { useEffect, useRef } from "react"
import {
  CircleUserRound,
  DollarSign,
  Mail,
  MapPin,
  MessageCircle,
  Phone,
  User,
} from "lucide-react"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import { cn } from "@/lib/utils"
import {
  FormFieldIcon,
  FormSection,
  FormTextareaIcon,
} from "@/components/shared/forms/FormSection"
import {
  adminFormFieldErrorClass,
  adminFormInputClass,
  adminFormInputCompactClass,
  adminFormLabelClass,
  adminFormSwitchRowClass,
  adminFormTextareaClass,
} from "@/components/shared/forms/administrative-form-styles"
import { formatOpeningBalanceSummary } from "@/features/suppliers"
import type { CreateSupplierInput, Supplier, UpdateSupplierInput } from "@/features/suppliers"

export type OpeningBalanceDirection = "supplier_due" | "supplier_credit"

export type SupplierFormState = {
  name: string
  contactPerson: string
  phone: string
  secondaryPhone: string
  whatsapp: string
  email: string
  address: string
  creditLimit: string
  openingBalanceAmount: string
  openingBalanceDirection: OpeningBalanceDirection
  notes: string
  isActive: boolean
}

export function emptySupplierForm(): SupplierFormState {
  return {
    name: "",
    contactPerson: "",
    phone: "",
    secondaryPhone: "",
    whatsapp: "",
    email: "",
    address: "",
    creditLimit: "",
    openingBalanceAmount: "0",
    openingBalanceDirection: "supplier_due",
    notes: "",
    isActive: true,
  }
}

export function supplierToForm(supplier: Supplier): SupplierFormState {
  return {
    name: supplier.name ?? "",
    contactPerson: supplier.contact_person ?? "",
    phone: supplier.phone ?? "",
    secondaryPhone: supplier.secondary_phone ?? "",
    whatsapp: supplier.whatsapp ?? "",
    email: supplier.email ?? "",
    address: supplier.address ?? "",
    creditLimit: supplier.credit_limit != null ? String(supplier.credit_limit) : "",
    openingBalanceAmount: "0",
    openingBalanceDirection: "supplier_due",
    notes: supplier.notes ?? "",
    isActive: supplier.is_active,
  }
}

export function normalizeOpeningBalanceForApi(form: SupplierFormState): number {
  const amount = Math.abs(Number.parseFloat(form.openingBalanceAmount || "0") || 0)
  const sign = form.openingBalanceDirection === "supplier_credit" ? -1 : 1
  return amount * sign
}

/** Create payload — code is auto-generated by backend; never sent. */
export function formToCreatePayload(form: SupplierFormState): CreateSupplierInput {
  const payload: CreateSupplierInput = {
    name: form.name.trim(),
    is_active: form.isActive,
    opening_balance: normalizeOpeningBalanceForApi(form),
  }
  if (form.contactPerson.trim()) payload.contact_person = form.contactPerson.trim()
  if (form.phone.trim()) payload.phone = form.phone.trim()
  if (form.secondaryPhone.trim()) payload.secondary_phone = form.secondaryPhone.trim()
  if (form.whatsapp.trim()) payload.whatsapp = form.whatsapp.trim()
  if (form.email.trim()) payload.email = form.email.trim()
  if (form.address.trim()) payload.address = form.address.trim()
  if (form.notes.trim()) payload.notes = form.notes.trim()
  if (form.creditLimit.trim()) {
    const n = Number.parseFloat(form.creditLimit)
    if (Number.isFinite(n)) payload.credit_limit = n
  }
  return payload
}

/** Update payload — opening/current balance cannot be changed from the UI. */
export function formToUpdatePayload(form: SupplierFormState): UpdateSupplierInput {
  const payload: UpdateSupplierInput = {
    name: form.name.trim(),
    contact_person: form.contactPerson.trim() || null,
    phone: form.phone.trim() || null,
    secondary_phone: form.secondaryPhone.trim() || null,
    whatsapp: form.whatsapp.trim() || null,
    email: form.email.trim() || null,
    address: form.address.trim() || null,
    notes: form.notes.trim() || null,
    is_active: form.isActive,
  }
  if (form.creditLimit.trim()) {
    const n = Number.parseFloat(form.creditLimit)
    payload.credit_limit = Number.isFinite(n) ? n : null
  } else {
    payload.credit_limit = null
  }
  return payload
}

type SupplierFormFieldsProps = {
  form: SupplierFormState
  onChange: (next: SupplierFormState) => void
  idPrefix: string
  mode: "create" | "edit"
  supplier?: Supplier | null
  fieldErrors?: Record<string, string[]>
  nameFieldAutoFocus?: boolean
  formKey?: string
}

function fieldError(errors: Record<string, string[]> | undefined, key: string): string | undefined {
  return errors?.[key]?.[0]
}

function sanitizeOpeningAmount(value: string): string {
  return value.replace(/[^\d.,]/g, "").replace(/-/g, "")
}

export function SupplierFormFields({
  form,
  onChange,
  idPrefix,
  mode,
  supplier,
  fieldErrors,
  nameFieldAutoFocus,
  formKey,
}: SupplierFormFieldsProps) {
  const set = (patch: Partial<SupplierFormState>) => onChange({ ...form, ...patch })
  const whatsappLinkedToPhoneRef = useRef(true)

  useEffect(() => {
    whatsappLinkedToPhoneRef.current =
      !form.whatsapp.trim() || form.whatsapp.trim() === form.phone.trim()
  }, [formKey])

  const handlePhoneChange = (phone: string) => {
    if (whatsappLinkedToPhoneRef.current) {
      set({ phone, whatsapp: phone })
    } else {
      set({ phone })
    }
  }

  const handleWhatsappChange = (whatsapp: string) => {
    whatsappLinkedToPhoneRef.current = whatsapp.trim() === form.phone.trim()
    set({ whatsapp })
  }

  return (
    <div className="space-y-3.5">
      <FormSection icon={CircleUserRound} title="معلومات المورد">
        <div className="grid grid-cols-1 gap-3.5 sm:grid-cols-2 sm:items-start">
          <div className="space-y-1.5 sm:col-span-2">
            <Label htmlFor={`${idPrefix}-name`} className={adminFormLabelClass}>
              اسم المورد <span className="text-destructive">*</span>
            </Label>
            <div className="relative w-full min-w-0">
              <FormFieldIcon>
                <User className="size-4" />
              </FormFieldIcon>
              <Input
                id={`${idPrefix}-name`}
                name="name"
                value={form.name}
                onChange={(ev) => set({ name: ev.target.value })}
                autoFocus={nameFieldAutoFocus}
                placeholder="مثال: شركة النخبة للتوريدات"
                className={adminFormInputClass}
              />
            </div>
            {fieldError(fieldErrors, "name") ? (
              <p className={adminFormFieldErrorClass} role="alert">
                {fieldError(fieldErrors, "name")}
              </p>
            ) : null}
          </div>

          <div className="space-y-1.5 sm:col-span-2">
            <Label htmlFor={`${idPrefix}-contact`} className={adminFormLabelClass}>
              اسم جهة الاتصال (اختياري)
            </Label>
            <div className="relative w-full min-w-0">
              <FormFieldIcon>
                <User className="size-4" />
              </FormFieldIcon>
              <Input
                id={`${idPrefix}-contact`}
                name="contactPerson"
                value={form.contactPerson}
                onChange={(ev) => set({ contactPerson: ev.target.value })}
                placeholder="مثال: أحمد محمد"
                className={adminFormInputClass}
              />
            </div>
          </div>

          <div className={adminFormSwitchRowClass}>
            <Label htmlFor={`${idPrefix}-isActive`} className={adminFormLabelClass}>
              الحالة (فعال)
            </Label>
            <Switch
              id={`${idPrefix}-isActive`}
              checked={form.isActive}
              onCheckedChange={(c) => set({ isActive: Boolean(c) })}
            />
          </div>
        </div>
      </FormSection>

      <FormSection icon={Phone} title="معلومات التواصل">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <div className="space-y-1.5">
            <Label htmlFor={`${idPrefix}-phone`} className={adminFormLabelClass}>
              الهاتف
            </Label>
            <div className="relative w-full min-w-0">
              <FormFieldIcon>
                <Phone className="size-4" />
              </FormFieldIcon>
              <Input
                id={`${idPrefix}-phone`}
                name="phone"
                type="tel"
                value={form.phone}
                onChange={(ev) => handlePhoneChange(ev.target.value)}
                autoComplete="tel"
                placeholder="05XXXXXXXX"
                className={adminFormInputCompactClass}
                dir="ltr"
              />
            </div>
          </div>

          <div className="space-y-1.5">
            <Label htmlFor={`${idPrefix}-secondaryPhone`} className={adminFormLabelClass}>
              هاتف إضافي
            </Label>
            <div className="relative w-full min-w-0">
              <FormFieldIcon>
                <Phone className="size-4" />
              </FormFieldIcon>
              <Input
                id={`${idPrefix}-secondaryPhone`}
                name="secondaryPhone"
                type="tel"
                value={form.secondaryPhone}
                onChange={(ev) => set({ secondaryPhone: ev.target.value })}
                placeholder="05XXXXXXXX"
                className={adminFormInputCompactClass}
                dir="ltr"
              />
            </div>
          </div>

          <div className="space-y-1.5">
            <Label htmlFor={`${idPrefix}-whatsapp`} className={adminFormLabelClass}>
              واتساب
            </Label>
            <div className="relative w-full min-w-0">
              <FormFieldIcon>
                <MessageCircle className="size-4" />
              </FormFieldIcon>
              <Input
                id={`${idPrefix}-whatsapp`}
                name="whatsapp"
                type="tel"
                value={form.whatsapp}
                onChange={(ev) => handleWhatsappChange(ev.target.value)}
                placeholder="05XXXXXXXX"
                className={adminFormInputCompactClass}
                dir="ltr"
              />
            </div>
          </div>

          <div className="space-y-1.5">
            <Label htmlFor={`${idPrefix}-email`} className={adminFormLabelClass}>
              البريد الإلكتروني
            </Label>
            <div className="relative w-full min-w-0">
              <FormFieldIcon>
                <Mail className="size-4" />
              </FormFieldIcon>
              <Input
                id={`${idPrefix}-email`}
                name="email"
                type="email"
                value={form.email}
                onChange={(ev) => set({ email: ev.target.value })}
                autoComplete="email"
                placeholder="example@email.com"
                className={adminFormInputCompactClass}
                dir="ltr"
              />
            </div>
            {fieldError(fieldErrors, "email") ? (
              <p className={adminFormFieldErrorClass} role="alert">
                {fieldError(fieldErrors, "email")}
              </p>
            ) : null}
          </div>

          <div className="space-y-1.5 sm:col-span-2">
            <Label htmlFor={`${idPrefix}-address`} className={adminFormLabelClass}>
              العنوان
            </Label>
            <div className="relative w-full min-w-0">
              <FormTextareaIcon>
                <MapPin className="size-4" />
              </FormTextareaIcon>
              <Textarea
                id={`${idPrefix}-address`}
                name="address"
                value={form.address}
                onChange={(ev) => set({ address: ev.target.value })}
                autoComplete="street-address"
                placeholder="أدخل عنوان المورد (اختياري)"
                className={adminFormTextareaClass}
              />
            </div>
          </div>
        </div>
      </FormSection>

      <FormSection icon={DollarSign} title="المعلومات المالية والملاحظات">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 sm:items-start">
          <div className="space-y-1.5">
            <Label htmlFor={`${idPrefix}-creditLimit`} className={adminFormLabelClass}>
              الحد الائتماني
            </Label>
            <div className="relative w-full min-w-0">
              <FormFieldIcon>
                <DollarSign className="size-4" />
              </FormFieldIcon>
              <Input
                id={`${idPrefix}-creditLimit`}
                name="creditLimit"
                inputMode="decimal"
                value={form.creditLimit}
                onChange={(ev) => set({ creditLimit: ev.target.value })}
                placeholder="مثال: 5,000"
                className={adminFormInputCompactClass}
                dir="ltr"
              />
            </div>
            {fieldError(fieldErrors, "credit_limit") ? (
              <p className={adminFormFieldErrorClass} role="alert">
                {fieldError(fieldErrors, "credit_limit")}
              </p>
            ) : null}
          </div>

          {mode === "create" ? (
            <div className="space-y-1.5">
              <Label htmlFor={`${idPrefix}-openingBalance`} className={adminFormLabelClass}>
                الرصيد الافتتاحي
              </Label>
              <div className="flex items-stretch gap-2">
                <div className="relative min-w-0 flex-1">
                  <FormFieldIcon>
                    <DollarSign className="size-4" />
                  </FormFieldIcon>
                  <Input
                    id={`${idPrefix}-openingBalance`}
                    name="openingBalanceAmount"
                    inputMode="decimal"
                    min={0}
                    value={form.openingBalanceAmount}
                    onChange={(ev) =>
                      set({ openingBalanceAmount: sanitizeOpeningAmount(ev.target.value) })
                    }
                    placeholder="مثال: 0.00"
                    className={adminFormInputCompactClass}
                    dir="ltr"
                  />
                </div>
                <div
                  className="inline-flex shrink-0 overflow-hidden rounded-lg border border-border/60"
                  role="group"
                  aria-label="اتجاه الرصيد الافتتاحي"
                >
                  {(
                    [
                      { value: "supplier_due", label: "له" },
                      { value: "supplier_credit", label: "عليه" },
                    ] as const
                  ).map((option) => {
                    const selected = form.openingBalanceDirection === option.value
                    return (
                      <button
                        key={option.value}
                        type="button"
                        className={cn(
                          "min-w-12 px-3 py-2 text-sm font-medium transition-colors",
                          selected
                            ? "bg-primary text-primary-foreground"
                            : "bg-background text-muted-foreground hover:bg-muted/60"
                        )}
                        onClick={() => set({ openingBalanceDirection: option.value })}
                      >
                        {option.label}
                      </button>
                    )
                  })}
                </div>
              </div>
              {fieldError(fieldErrors, "opening_balance") ? (
                <p className={adminFormFieldErrorClass} role="alert">
                  {fieldError(fieldErrors, "opening_balance")}
                </p>
              ) : null}
            </div>
          ) : supplier ? (
            <div className="space-y-1.5">
              <Label className={adminFormLabelClass}>الرصيد الافتتاحي</Label>
              <p className="rounded-lg border border-border/60 bg-muted/20 px-3 py-2.5 text-sm" dir="ltr">
                {formatOpeningBalanceSummary(supplier.opening_balance)}
              </p>
            </div>
          ) : null}

          <p className="text-xs leading-relaxed text-muted-foreground sm:col-span-2">
            ملاحظة: «له» تعني أن عليكم مبلغًا للمورد، و«عليه» تعني أن لكم رصيدًا عند المورد.
          </p>

          <div className="space-y-1.5 sm:col-span-2">
            <Label htmlFor={`${idPrefix}-notes`} className={adminFormLabelClass}>
              ملاحظات
            </Label>
            <Textarea
              id={`${idPrefix}-notes`}
              name="notes"
              value={form.notes}
              onChange={(ev) => set({ notes: ev.target.value })}
              placeholder="أدخل أي ملاحظات إضافية عن المورد (اختياري)"
              className="min-h-[80px] rounded-lg"
            />
            {fieldError(fieldErrors, "notes") ? (
              <p className={adminFormFieldErrorClass} role="alert">
                {fieldError(fieldErrors, "notes")}
              </p>
            ) : null}
          </div>
        </div>
      </FormSection>
    </div>
  )
}
