/**
 * Shapes from Laravel `CustomerResource`, index/store/update requests.
 * Keys match backend (snake_case) exactly.
 */

export type CustomerUserRef = {
  id: number
  name: string
}

export type CustomerLastActivity = {
  type: string
  number: string
  date: string
}

export type CustomerType = "retail" | "wholesale" | "car"

export type Customer = {
  id: number
  code: string | null
  name: string
  contact_person: string | null
  customer_type: CustomerType
  car_number: string | null
  phone: string | null
  secondary_phone: string | null
  whatsapp: string | null
  email: string | null
  address: string | null
  opening_balance: string | number | null
  current_balance: string | number | null
  credit_limit: string | number | null
  is_active: boolean
  notes: string | null
  last_activity: CustomerLastActivity | null
  created_at: string | null
  updated_at: string | null
  created_by?: CustomerUserRef
  updated_by?: CustomerUserRef
}

export type CustomersListMeta = {
  total: number
  current_page: number
  per_page: number
  last_page: number
}

export type BalanceStatusFilter = "receivable" | "credit" | "settled"

/** Direction for min/max balance range filter (عليه لنا / له عندنا). */
export type BalanceRangeDirection = "receivable" | "credit"

/** `IndexCustomerRequest` + Laravel paginator `page`. */
export type CustomersListFilters = {
  search?: string
  is_active?: boolean
  customer_type?: CustomerType
  balance_status?: BalanceStatusFilter
  balance_min?: number
  balance_max?: number
  sort_by?: string
  sort_direction?: "asc" | "desc"
  page?: number
  per_page?: number
}

/** `StoreCustomerRequest` — code is auto-generated by backend. */
export type CreateCustomerInput = {
  name: string
  customer_type: CustomerType
  contact_person?: string | null
  car_number?: string | null
  phone?: string | null
  secondary_phone?: string | null
  whatsapp?: string | null
  email?: string | null
  address?: string | null
  opening_balance?: number | null
  credit_limit?: number | null
  is_active?: boolean
  notes?: string | null
}

/** `UpdateCustomerRequest` — partial updates only; balances are not editable. */
export type UpdateCustomerInput = {
  name?: string
  customer_type?: CustomerType
  contact_person?: string | null
  car_number?: string | null
  phone?: string | null
  secondary_phone?: string | null
  whatsapp?: string | null
  email?: string | null
  address?: string | null
  credit_limit?: number | null
  is_active?: boolean
  notes?: string | null
}

/** Shape returned by GET /api/bff/customers/summary */
export type CustomerSummaryResponse = {
  active_customers_count: number
  sales_total_in_period: number | string
  customer_receivables_total: number | string
  customer_credit_total: number | string
}

export type CustomersSummaryData = {
  activeCustomersCount: number | null
  salesTotalInPeriod: string | null
  customerReceivablesTotal: string | null
  customerCreditTotal: string | null
}
