"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { ChevronLeft, CircleDollarSign, Loader2, MinusCircle, Package, Scale, SlidersHorizontal } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Skeleton } from "@/components/ui/skeleton"
import { ItemsPeriodControls } from "@/components/items/ItemsPeriodControls"
import { DateRangeDialog } from "@/components/shared/DateRangeDialog"
import { defaultInventoryPeriod, formatInventoryCost, formatInventoryDate, formatInventoryMoney, formatInventoryQuantity, INVENTORY_ITEM_TYPE_LABELS_AR, INVENTORY_PERIOD_STORAGE_KEY, readInventoryPeriod, resolveInventoryPeriod, type InventoryCustomPeriod, type InventoryPeriodPreset, useInventoryItemDetails } from "@/src/features/inventory"
import { InventoryAdjustmentDialog } from "./InventoryAdjustmentDialog"
import { InventoryMovementLedger } from "./InventoryMovementLedger"
import { InventoryStockStatusBadge } from "./InventoryStockStatusBadge"
import { InventoryWithdrawalDialog } from "./InventoryWithdrawalDialog"

export function InventoryItemDetailsView({ itemId }: { itemId: number }) {
  const [hydrated, setHydrated] = useState(false); const [preset, setPreset] = useState<InventoryPeriodPreset>("current_month"); const [custom, setCustom] = useState<InventoryCustomPeriod | null>(null); const [customOpen, setCustomOpen] = useState(false); const [withdrawOpen, setWithdrawOpen] = useState(false); const [adjustOpen, setAdjustOpen] = useState(false)
  useEffect(() => { const timer = window.setTimeout(() => { const period = readInventoryPeriod(); setPreset(period.preset); setCustom(period.custom); setHydrated(true) }, 0); return () => window.clearTimeout(timer) }, [])
  useEffect(() => { if (hydrated) localStorage.setItem(INVENTORY_PERIOD_STORAGE_KEY, JSON.stringify({ preset, custom })) }, [preset, custom, hydrated])
  const dateRange = resolveInventoryPeriod(preset, custom); const result = useInventoryItemDetails(itemId, dateRange, hydrated); const item = result.item
  function changePreset(value: InventoryPeriodPreset) { if (value === "custom") { setCustom((v) => v ?? defaultInventoryPeriod()); setCustomOpen(true) }; setPreset(value) }
  if (result.isLoading) return <div className="space-y-5" dir="rtl">{Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-32 rounded-2xl" />)}</div>
  if (result.error || !item) return <div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-8 text-center text-destructive" dir="rtl"><Loader2 className="mx-auto mb-2 size-5" />تعذر تحميل بيانات مخزون الصنف.</div>
  const latest = item.latest_movement
  return <div className="space-y-6 pb-10" dir="rtl" lang="ar"><div className="relative overflow-hidden rounded-3xl border bg-linear-to-bl from-primary/10 via-primary/5 to-transparent p-6 shadow-sm"><div className="flex flex-col gap-5 md:flex-row md:items-center"><div className="flex size-16 items-center justify-center rounded-2xl border bg-card text-primary shadow"><Package className="size-8" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold">{item.name}</h1><Badge variant="secondary">{INVENTORY_ITEM_TYPE_LABELS_AR[item.item_type]}</Badge><InventoryStockStatusBadge item={item} reorderLabel /></div><p className="mt-1 font-mono text-sm text-muted-foreground" dir="ltr">{item.code}</p></div><div className="flex flex-wrap gap-2"><ItemsPeriodControls preset={preset} onPresetChange={changePreset} /><Button onClick={() => setWithdrawOpen(true)} className="gap-2 rounded-xl"><MinusCircle className="size-4" />سحب كمية</Button><Button variant="outline" onClick={() => setAdjustOpen(true)} className="gap-2 rounded-xl"><SlidersHorizontal className="size-4" />تسوية المخزون</Button><Button variant="outline" asChild><Link href="/dashboard/inventory"><ChevronLeft className="size-4" />المستودع</Link></Button></div></div></div>
    <Section title="ملخص الرصيد"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Stat icon={Scale} label="الكمية الحالية" value={formatInventoryQuantity(item.current_quantity_kg)} /><Stat icon={CircleDollarSign} label="متوسط التكلفة" value={formatInventoryCost(item.average_cost)} /><Stat icon={CircleDollarSign} label="قيمة المخزون" value={formatInventoryMoney(item.stock_value)} /><Stat icon={CircleDollarSign} label="آخر سعر شراء" value={formatInventoryCost(item.last_purchase_price)} /><Stat icon={Scale} label="حد إعادة الطلب" value={formatInventoryQuantity(item.minimum_quantity_kg)} /><div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">حالة المخزون</p><div className="mt-2"><InventoryStockStatusBadge item={item} reorderLabel /></div></div></div></Section>
    <div className="grid gap-5 lg:grid-cols-2"><Section title="معلومات الصنف"><Rows rows={[["الاسم", item.name], ["الكود", item.code], ["النوع", INVENTORY_ITEM_TYPE_LABELS_AR[item.item_type]], ["الوحدة", "كيلوغرام (kg)"], ["الحالة", item.is_active ? "فعال" : "موقوف"], ["ملاحظات", item.notes || "—"]]} /></Section><Section title="آخر حركة"><Rows rows={latest ? [["نوع الحركة", latest.movement_label_ar], ["المرجع", latest.source_number || "—"], ["الكمية", formatInventoryQuantity(latest.quantity_kg)], ["التاريخ", formatInventoryDate(latest.movement_date, true)], ["المستخدم", latest.created_by?.name || "—"]] : [["الحركة", "لا توجد حركة بعد"]]} /></Section></div>
    <Section title="حركات الصنف"><InventoryMovementLedger itemId={item.id} dateRange={dateRange} /></Section>
    <Section title="معلومات النظام"><Rows rows={[["تاريخ الإنشاء", formatInventoryDate(item.created_at, true)], ["أنشئ بواسطة", item.created_by?.name || "—"], ["آخر تحديث", formatInventoryDate(item.updated_at, true)], ["حدّث بواسطة", item.updated_by?.name || "—"]]} /></Section>
    <DateRangeDialog open={customOpen} onOpenChange={setCustomOpen} from={custom?.from ?? defaultInventoryPeriod().from} to={custom?.to ?? defaultInventoryPeriod().to} onApply={(from, to) => { setCustom({ from, to }); setPreset("custom"); setCustomOpen(false) }} /><InventoryWithdrawalDialog key={withdrawOpen ? "withdrawal-open" : "withdrawal-closed"} item={item} open={withdrawOpen} onOpenChange={setWithdrawOpen} /><InventoryAdjustmentDialog key={adjustOpen ? "adjustment-open" : "adjustment-closed"} item={item} open={adjustOpen} onOpenChange={setAdjustOpen} />
  </div>
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-3"><h2 className="text-sm font-semibold text-muted-foreground">{title}</h2><div className="rounded-2xl border bg-card/50 p-4 shadow-sm">{children}</div></section> }
function Stat({ icon: Icon, label, value }: { icon: React.ElementType; label: string; value: string }) { return <div className="rounded-xl border bg-muted/10 p-3"><p className="flex items-center gap-1 text-xs text-muted-foreground"><Icon className="size-3.5" />{label}</p><p className="mt-2 font-semibold" dir="ltr">{value}</p></div> }
function Rows({ rows }: { rows: [string, React.ReactNode][] }) { return <div className="space-y-3">{rows.map(([label, value]) => <div key={label} className="flex justify-between gap-4 text-sm"><span className="text-muted-foreground">{label}</span><span className="font-medium">{value}</span></div>)}</div> }
