"use client"

import { MoreHorizontal, PackageSearch } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter, CardHeader } from "@/components/ui/card"
import { ContextMenu, ContextMenuTrigger } from "@/components/ui/context-menu"
import { DropdownMenu, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Skeleton } from "@/components/ui/skeleton"
import { formatInventoryCost, formatInventoryDate, formatInventoryMoney, formatInventoryQuantity, INVENTORY_ITEM_TYPE_LABELS_AR, inventoryNumber, type InventoryItem, type InventoryPaginationMeta } from "@/src/features/inventory"
import { InventoryStockStatusBadge } from "./InventoryStockStatusBadge"
import { InventoryRowActionsMenuContent, InventoryRowContextMenuContent, type InventoryRowActionCallbacks } from "./inventory-row-actions-menu"

export function InventoryCards({ items, meta, isLoading, page, onPageChange, actions }: { items: InventoryItem[]; meta?: InventoryPaginationMeta; isLoading: boolean; page: number; onPageChange: (page: number) => void; actions: (item: InventoryItem) => InventoryRowActionCallbacks }) {
  if (isLoading) return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <Skeleton key={i} className="h-72 rounded-2xl" />)}</div>
  if (items.length === 0) return <div className="flex min-h-72 flex-col items-center justify-center gap-3 text-muted-foreground"><PackageSearch className="size-10" />لا توجد أصناف ضمن الفلاتر الحالية.</div>
  return <div className="space-y-4"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <ContextMenu key={item.id}><ContextMenuTrigger asChild><Card className="overflow-hidden rounded-2xl transition hover:border-primary/30 hover:shadow-md"><CardHeader className="flex-row items-start justify-between gap-3"><div><h3 className="font-bold">{item.name}</h3><p className="font-mono text-xs text-muted-foreground" dir="ltr">{item.code}</p><div className="mt-2 flex gap-2"><Badge variant="secondary">{INVENTORY_ITEM_TYPE_LABELS_AR[item.item_type]}</Badge><InventoryStockStatusBadge item={item} reorderLabel /></div></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon-sm"><MoreHorizontal className="size-4" /></Button></DropdownMenuTrigger><InventoryRowActionsMenuContent {...actions(item)} /></DropdownMenu></CardHeader><CardContent className="grid grid-cols-2 gap-3 text-sm"><Info label="الكمية الحالية" value={formatInventoryQuantity(item.current_quantity_kg)} /><Info label="متوسط التكلفة" value={formatInventoryCost(item.average_cost)} /><Info label="قيمة المخزون" value={formatInventoryMoney(item.stock_value)} /><Info label="الحد الأدنى" value={inventoryNumber(item.minimum_quantity_kg) ? formatInventoryQuantity(item.minimum_quantity_kg) : "غير محدد"} /><div className="col-span-2"><Info label="آخر حركة" value={item.last_activity ? `${item.last_activity.label} · ${formatInventoryDate(item.last_activity.date)}` : "لا توجد حركة بعد"} /></div></CardContent><CardFooter className="grid grid-cols-3 gap-2 border-t bg-muted/10 pt-4"><Button variant="outline" size="sm" onClick={actions(item).onDetails}>التفاصيل</Button><Button variant="outline" size="sm" onClick={actions(item).onWithdraw}>سحب</Button><Button variant="outline" size="sm" onClick={actions(item).onAdjust}>تسوية</Button></CardFooter></Card></ContextMenuTrigger><InventoryRowContextMenuContent {...actions(item)} /></ContextMenu>)}</div>{(meta?.last_page ?? 1) > 1 ? <div className="flex justify-center gap-2"><Button variant="outline" disabled={page <= 1} onClick={() => onPageChange(page - 1)}>السابق</Button><Button variant="outline" disabled={page >= (meta?.last_page ?? 1)} onClick={() => onPageChange(page + 1)}>التالي</Button></div> : null}</div>
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-muted/15 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold" dir="ltr">{value}</p></div> }
