"use client"

import { useState } from "react"
import { ClipboardList, Loader2, SlidersHorizontal, X } from "lucide-react"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { ADJUSTMENT_REASON_LABELS_AR, formatInventoryCost, formatInventoryQuantity, inventoryNumber, type AdjustmentReason, type InventoryItem, useInventoryActions } from "@/src/features/inventory"
import { InventoryStockStatusBadge } from "./InventoryStockStatusBadge"

export function InventoryAdjustmentDialog({ item, open, onOpenChange }: { item: InventoryItem | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  const [actual, setActual] = useState(""); const [reason, setReason] = useState<AdjustmentReason>("stock_count"); const [unitCost, setUnitCost] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const { adjust } = useInventoryActions()
  const current = inventoryNumber(item?.current_quantity_kg); const actualValue = inventoryNumber(actual); const difference = actual.trim() ? actualValue - current : 0; const needsCost = difference > 0 && inventoryNumber(item?.average_cost) <= 0
  function handleOpenChange(next: boolean) { if (!next) { setActual(""); setReason("stock_count"); setUnitCost(""); setNotes(""); setError("") }; onOpenChange(next) }
  async function submit() { if (!item) return; if (actual.trim() === "" || actualValue < 0) { setError("أدخل كمية فعلية صحيحة."); return }; if (Math.abs(difference) < 0.0005) { setError("لا يوجد فرق بين الكمية الحالية والكمية الفعلية."); return }; if (needsCost && inventoryNumber(unitCost) <= 0) { setError("أدخل تكلفة الوحدة لتسجيل الزيادة لهذا الصنف."); return }; setSubmitting(true); setError(""); try { await adjust({ item_id: item.id, actual_quantity_kg: actualValue, reason, unit_cost: needsCost ? inventoryNumber(unitCost) : undefined, notes: notes.trim() || null }); handleOpenChange(false) } catch { /* toast handled */ } finally { setSubmitting(false) } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent dir="rtl" showCloseButton={false} className="flex max-h-[92vh] flex-col gap-0 overflow-hidden rounded-2xl p-0 sm:max-w-2xl"><DialogHeader className="border-b bg-linear-to-bl from-amber-500/10 via-background to-background px-6 py-5 text-right sm:text-right"><div className="flex items-start gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-amber-500/10 text-amber-600"><SlidersHorizontal className="size-5" /></span><div className="flex-1"><DialogTitle>تسوية المخزون</DialogTitle><DialogDescription className="mt-1.5 leading-relaxed">أدخل الكمية الفعلية بعد الجرد، وسيحسب النظام فرق التسوية ويسجل حركة مخزون.</DialogDescription><p className="mt-2 text-xs text-muted-foreground"><span className="text-destructive">*</span> يشير إلى حقل مطلوب.</p></div><Button variant="ghost" size="icon-sm" onClick={() => onOpenChange(false)}><X className="size-4" /></Button></div></DialogHeader>
    <div className="min-h-0 flex-1 space-y-5 overflow-y-auto px-6 py-5">{item ? <section className="space-y-2"><h3 className="text-sm font-semibold">معلومات الصنف</h3><div className="grid gap-3 rounded-2xl border bg-muted/20 p-4 sm:grid-cols-2"><div><p className="font-semibold">{item.name}</p><p className="font-mono text-xs text-muted-foreground" dir="ltr">{item.code}</p></div><div className="flex flex-wrap items-center gap-2 sm:justify-end"><InventoryStockStatusBadge item={item} /><span dir="ltr">{formatInventoryQuantity(current)}</span><span dir="ltr">{formatInventoryCost(item.average_cost)}</span></div></div></section> : null}
      <section className="space-y-4"><h3 className="text-sm font-semibold">بيانات التسوية</h3><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>الكمية الفعلية (كغ) <span className="text-destructive">*</span></Label><Input value={actual} onChange={(e) => setActual(e.target.value)} inputMode="decimal" placeholder="مثال: 97.000" dir="ltr" /></div><div className="space-y-2"><Label>سبب التسوية <span className="text-destructive">*</span></Label><Select value={reason} onValueChange={(v) => setReason(v as AdjustmentReason)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(ADJUSTMENT_REASON_LABELS_AR).map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></div></div>{needsCost ? <div className="space-y-2"><Label>تكلفة الوحدة (USD / كغ) <span className="text-destructive">*</span></Label><Input value={unitCost} onChange={(e) => setUnitCost(e.target.value)} inputMode="decimal" dir="ltr" /></div> : null}
      <div className="grid gap-2 rounded-xl border bg-muted/20 p-3 text-sm sm:grid-cols-3"><span>الحالية: <strong dir="ltr">{formatInventoryQuantity(current)}</strong></span><span>الفعلية: <strong dir="ltr">{actual.trim() ? formatInventoryQuantity(actualValue) : "—"}</strong></span><span className={difference > 0 ? "text-emerald-700" : difference < 0 ? "text-rose-700" : "text-muted-foreground"}>فرق التسوية: <strong dir="ltr">{difference > 0 ? `زيادة: +${formatInventoryQuantity(difference)}` : difference < 0 ? `نقص: -${formatInventoryQuantity(Math.abs(difference))}` : "لا يوجد فرق"}</strong></span></div>{error ? <p className="text-sm text-destructive">{error}</p> : null}
      <Accordion type="single" collapsible><AccordionItem value="notes" className="overflow-hidden rounded-xl border"><AccordionTrigger className="px-4 hover:no-underline"><span className="flex items-center gap-2"><ClipboardList className="size-4" />ملاحظات</span></AccordionTrigger><AccordionContent className="px-4 pb-4"><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="ملاحظات التسوية (اختياري)" /></AccordionContent></AccordionItem></Accordion></section></div>
    <div className="flex gap-2 border-t bg-muted/20 px-6 py-4"><Button onClick={submit} disabled={submitting || !item} className="gap-2 rounded-xl">{submitting ? <Loader2 className="size-4 animate-spin" /> : <SlidersHorizontal className="size-4" />}تسجيل التسوية</Button><Button variant="outline" onClick={() => onOpenChange(false)} className="rounded-xl">إلغاء</Button></div>
  </DialogContent></Dialog>
}
