/**
 * Shapes from Laravel `ItemResource`, index/store/update requests.
 * Keys match backend (snake_case) exactly.
 */

export type ItemUserRef = {
  id: number
  name: string
}

export type ItemLastActivity = {
  type: string
  label: string
  number: string | null
  date: string
}

export type ItemType = "raw" | "ready"

export type StockStatus = "available" | "low" | "out_of_stock"

/** API list filter — includes composite reorder_required (low OR out_of_stock with min > 0). */
export type StockStatusFilter = StockStatus | "reorder_required"

export type Item = {
  id: number
  code: string | null
  name: string
  item_type: ItemType
  unit: string | null
  current_quantity_kg: string | number | null
  average_cost: string | number | null
  last_purchase_price: string | number | null
  minimum_quantity_kg: string | number | null
  auto_create_default_product: boolean
  is_active: boolean
  notes: string | null
  last_activity: ItemLastActivity | null
  created_at: string | null
  updated_at: string | null
  created_by?: ItemUserRef
  updated_by?: ItemUserRef
}

export type ItemsListMeta = {
  total: number
  current_page: number
  per_page: number
  last_page: number
}

/** `IndexItemRequest` + Laravel paginator `page`. */
export type ItemsListFilters = {
  search?: string
  is_active?: boolean
  item_type?: ItemType
  stock_status?: StockStatusFilter
  quantity_min?: number
  quantity_max?: number
  date_from?: string
  date_to?: string
  sort_by?: string
  sort_direction?: "asc" | "desc"
  page?: number
  per_page?: number
}

/** `StoreItemRequest` — code is auto-generated by backend. */
export type CreateItemInput = {
  name: string
  item_type: ItemType
  minimum_quantity_kg?: number | null
  auto_create_default_product?: boolean
  is_active?: boolean
  notes?: string | null
}

/** `UpdateItemRequest` — partial updates only; stock/cost are not editable. */
export type UpdateItemInput = {
  name?: string
  item_type?: ItemType
  minimum_quantity_kg?: number | null
  is_active?: boolean
  notes?: string | null
}

/** Shape returned by GET /api/bff/items/summary */
export type ItemSummaryResponse = {
  active_items_count: number
  raw_items_count: number
  ready_items_count: number
  reorder_required_count: number
  items_with_activity_in_period_count?: number
  inventory_in_quantity_in_period?: string | number
  inventory_out_quantity_in_period?: string | number
}
