import type { CategoryNode, LabTest } from "./lab-catalog-types"

/** Initial hierarchical categories */
export const initialCategoryTree: CategoryNode[] = [
  {
    id: "cat-hematology",
    name: "تحاليل الدم",
    iconKey: "hematology",
    children: [
      {
        id: "cat-hem-panel",
        name: "لوحة صورة الدم",
        iconKey: "hematology",
      },
      {
        id: "cat-hem-indices",
        name: "مؤشرات فردية",
        iconKey: "hematology",
      },
    ],
  },
  {
    id: "cat-biochemistry",
    name: "الكيمياء الحيوية",
    iconKey: "biochemistry",
    children: [
      {
        id: "cat-bio-glucose",
        name: "السكر والتمثيل",
        iconKey: "biochemistry",
      },
      {
        id: "cat-bio-lipids",
        name: "دهون",
        iconKey: "biochemistry",
      },
    ],
  },
  {
    id: "cat-renal",
    name: "وظائف الكلى",
    iconKey: "renal",
  },
  {
    id: "cat-liver",
    name: "وظائف الكبد",
    iconKey: "liver",
  },
  {
    id: "cat-thyroid",
    name: "الغدة الدرقية",
    iconKey: "thyroid",
  },
  {
    id: "cat-serology",
    name: "الفحوصات المصلية",
    iconKey: "serology",
    children: [
      {
        id: "cat-ser-hiv",
        name: "فيروسات",
        iconKey: "serology",
      },
      {
        id: "cat-ser-hep",
        name: "التهاب الكبد",
        iconKey: "serology",
      },
    ],
  },
]

export const initialTests: LabTest[] = [
  {
    id: "1",
    name: "صورة الدم الكاملة",
    code: "CBC",
    categoryId: "cat-hem-panel",
    price: 80,
    unit: "",
    referenceRange: "",
    fieldName: "CBC",
    resultType: "number",
    isActive: true,
  },
  {
    id: "2",
    name: "الهيموجلوبين",
    code: "HB",
    categoryId: "cat-hem-indices",
    price: 40,
    unit: "g/dL",
    referenceRange: "12-16",
    fieldName: "HB",
    resultType: "number",
    isActive: true,
  },
  {
    id: "3",
    name: "كريات الدم البيضاء",
    code: "WBC",
    categoryId: "cat-hem-indices",
    price: 45,
    unit: "×10³/µL",
    referenceRange: "4-11",
    fieldName: "WBC",
    resultType: "number",
    isActive: true,
  },
  {
    id: "4",
    name: "سكر الدم الصائم",
    code: "FBS",
    categoryId: "cat-bio-glucose",
    price: 35,
    unit: "mg/dL",
    referenceRange: "70-100",
    fieldName: "FBS",
    resultType: "number",
    isActive: true,
  },
  {
    id: "5",
    name: "السكر التراكمي",
    code: "HbA1c",
    categoryId: "cat-bio-glucose",
    price: 120,
    unit: "%",
    referenceRange: "4-5.6",
    fieldName: "HbA1c",
    resultType: "number",
    isActive: true,
  },
  {
    id: "6",
    name: "الكوليسترول الكلي",
    code: "CHOL",
    categoryId: "cat-bio-lipids",
    price: 60,
    unit: "mg/dL",
    referenceRange: "<200",
    fieldName: "CHOL",
    resultType: "number",
    isActive: true,
  },
  {
    id: "7",
    name: "اليوريا",
    code: "UREA",
    categoryId: "cat-renal",
    price: 45,
    unit: "mg/dL",
    referenceRange: "15-45",
    fieldName: "UREA",
    resultType: "number",
    isActive: true,
  },
  {
    id: "8",
    name: "الكرياتينين",
    code: "CREAT",
    categoryId: "cat-renal",
    price: 50,
    unit: "mg/dL",
    referenceRange: "0.6-1.2",
    fieldName: "CREAT",
    resultType: "number",
    isActive: true,
  },
  {
    id: "9",
    name: "إنزيم الكبد ALT",
    code: "ALT",
    categoryId: "cat-liver",
    price: 55,
    unit: "U/L",
    referenceRange: "7-56",
    fieldName: "ALT",
    resultType: "number",
    isActive: true,
  },
  {
    id: "10",
    name: "هرمون TSH",
    code: "TSH",
    categoryId: "cat-thyroid",
    price: 95,
    unit: "mIU/L",
    referenceRange: "0.4-4.0",
    fieldName: "TSH",
    resultType: "number",
    isActive: true,
  },
  {
    id: "11",
    name: "فحص HIV",
    code: "HIV",
    categoryId: "cat-ser-hiv",
    price: 150,
    unit: "",
    referenceRange: "سلبي",
    fieldName: "HIV",
    resultType: "select",
    selectOptions: "إيجابي, سلبي",
    isActive: true,
  },
  {
    id: "12",
    name: "فحص HBsAg",
    code: "HBsAg",
    categoryId: "cat-ser-hep",
    price: 120,
    unit: "",
    referenceRange: "سلبي",
    fieldName: "HBsAg",
    resultType: "select",
    selectOptions: "إيجابي, سلبي",
    isActive: true,
  },
]
