/**
 * Shapes from Laravel `SupplierResource`, `IndexSupplierRequest`, `StoreSupplierRequest`, `UpdateSupplierRequest`.
 * Keys match backend (snake_case) exactly.
 */

export type SupplierUserRef = {
  id: number
  name: string
}

export type SupplierLastActivity = {
  type: string
  number: string
  date: string
}

export type Supplier = {
  id: number
  code: string | null
  name: string
  phone: string | null
  secondary_phone: string | null
  whatsapp: string | null
  email: string | null
  address: string | null
  contact_person: string | null
  opening_balance: string | number | null
  current_balance: string | number | null
  credit_limit: string | number | null
  is_active: boolean
  notes: string | null
  last_activity: SupplierLastActivity | null
  created_at: string | null
  updated_at: string | null
  created_by?: SupplierUserRef
  updated_by?: SupplierUserRef
}

export type SuppliersListMeta = {
  total: number
  current_page: number
  per_page: number
  last_page: number
}

export type BalanceStatusFilter = "payable" | "credit" | "settled"

/** `IndexSupplierRequest` + Laravel paginator `page`. */
export type SuppliersListFilters = {
  search?: string
  is_active?: boolean
  balance_status?: BalanceStatusFilter
  balance_min?: number
  balance_max?: number
  sort_by?: string
  sort_direction?: "asc" | "desc"
  page?: number
  per_page?: number
}

/** `StoreSupplierRequest` — code is auto-generated by backend. */
export type CreateSupplierInput = {
  name: string
  phone?: string | null
  secondary_phone?: string | null
  whatsapp?: string | null
  email?: string | null
  address?: string | null
  contact_person?: string | null
  opening_balance?: number | null
  credit_limit?: number | null
  is_active?: boolean
  notes?: string | null
}

/** `UpdateSupplierRequest` — partial updates only. */
export type UpdateSupplierInput = {
  name?: string
  phone?: string | null
  secondary_phone?: string | null
  whatsapp?: string | null
  email?: string | null
  address?: string | null
  contact_person?: string | null
  opening_balance?: number | null
  credit_limit?: number | null
  is_active?: boolean
  notes?: string | null
}

/** Shape returned by GET /api/bff/suppliers/summary */
export type SupplierSummaryResponse = {
  active_suppliers_count: number
  purchases_total_in_period: number | string
  suppliers_payable_total: number | string
  supplier_credit_total: number | string
}

export type ReportCard = {
  key: string
  label: string
  value: string | number
  type: string
  description?: string
}

export type ReportPayload = {
  filters: Record<string, unknown>
  cards: ReportCard[]
  charts: unknown[]
  tables: Record<string, unknown>
}

export type SuppliersSummaryData = {
  activeSuppliersCount: number | null
  purchasesTotalInPeriod: string | null
  suppliersPayableTotal: string | null
  supplierCreditTotal: string | null
}
